title: Vaishnav Mukund Mankar
profile_img: /assets/img/profile.webp
icon_img: /assets/img/favicon.svg

name: "Vaishnav Mukund Mankar"
job: "〈Computer Engineering Student | PICT〉"

phone_number: +91 8668746433
address: Pune, India
email: vaishnav.mankar04@gmail.com
linkedin_username: vaishnav-mankar
github_username: myselfmankar
instagram_username: instagram
twitter_username: twitter
youtube_username: Vaishnav-Mankar
discord_username: mrtupperware
resume_url: /docs/vaishnav_mankar_resume.pdf
# Cloudflare Turnstile testing sitekey (always passes)
turnstile_sitekey: "1x00000000000000000000AA"
# blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl: ""

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
